FROM python:3.11-slim

WORKDIR /app

# Copiar requirements y instalar dependencias Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el script de ingesta MongoDB
COPY mongodb/ /app/mongodb/

# Variables de entorno por defecto
ENV MONGO_URI=mongodb://172.31.17.96:27017
ENV MONGO_DB=inventory
ENV MONGO_COLLECTION=ingredientes
ENV S3_BUCKET=bucket-mv-ingesta
ENV MODE=export

# Comando por defecto
CMD ["python", "mongodb/app.py"]
